# AUTO-GENERATED FILE — Regenerate with: make gen
"""Tests package."""

from __future__ import annotations

from types import MappingProxyType
from typing import TYPE_CHECKING

from flext_core.lazy import build_lazy_import_map, install_lazy_exports

if TYPE_CHECKING:
    from flext_infra import (
        check,
        codegen,
        codemod,
        collect_markdown_files,
        deps,
        detectors,
        docs,
        docs_main,
        fixers,
        gates,
        infra,
        maintenance,
        read_ignore_patterns,
        refactor,
        release,
        source_name,
        transformers,
        validate,
        workspace,
        write_docstring_sources,
        write_fenced_block_sources,
    )
    from flext_tests import (
        api,
        cli,
        config,
        core,
        d,
        e,
        from_json,
        h,
        install_local_packages,
        lazy_attribute,
        load_infra_report,
        r,
        services,
        settings,
        td,
        tf,
        tk,
        tm,
        to_json,
        to_jsonable_python,
        tv,
        x,
    )
    from flext_web import web

    from flext_quality import main, quality

    from . import helpers, unit
    from .base import TestsFlextQualityServiceBase, TestsFlextQualityServiceBase as s
    from .constants import TestsFlextQualityConstants, TestsFlextQualityConstants as c
    from .models import TestsFlextQualityModels, TestsFlextQualityModels as m
    from .protocols import TestsFlextQualityProtocols, TestsFlextQualityProtocols as p
    from .settings import TestsFlextQualitySettings
    from .typings import TestsFlextQualityTypes, TestsFlextQualityTypes as t
    from .utilities import TestsFlextQualityUtilities, TestsFlextQualityUtilities as u
__all__: tuple[str, ...] = (
    "TestsFlextQualityConstants",
    "TestsFlextQualityModels",
    "TestsFlextQualityProtocols",
    "TestsFlextQualityServiceBase",
    "TestsFlextQualitySettings",
    "TestsFlextQualityTypes",
    "TestsFlextQualityUtilities",
    "api",
    "c",
    "check",
    "cli",
    "codegen",
    "codemod",
    "collect_markdown_files",
    "config",
    "core",
    "d",
    "deps",
    "detectors",
    "docs",
    "docs_main",
    "e",
    "fixers",
    "from_json",
    "gates",
    "h",
    "helpers",
    "infra",
    "install_local_packages",
    "lazy_attribute",
    "load_infra_report",
    "m",
    "main",
    "maintenance",
    "p",
    "quality",
    "r",
    "read_ignore_patterns",
    "refactor",
    "release",
    "s",
    "services",
    "settings",
    "source_name",
    "t",
    "td",
    "tf",
    "tk",
    "tm",
    "to_json",
    "to_jsonable_python",
    "transformers",
    "tv",
    "u",
    "unit",
    "validate",
    "web",
    "workspace",
    "write_docstring_sources",
    "write_fenced_block_sources",
    "x",
)

_LAZY_IMPORTS = MappingProxyType(
    build_lazy_import_map(
        MappingProxyType({
            ".base": ("TestsFlextQualityServiceBase", "s"),
            ".constants": ("TestsFlextQualityConstants", "c"),
            ".helpers": ("helpers",),
            ".models": ("TestsFlextQualityModels", "m"),
            ".protocols": ("TestsFlextQualityProtocols", "p"),
            ".settings": ("TestsFlextQualitySettings",),
            ".typings": ("TestsFlextQualityTypes", "t"),
            ".unit": ("unit",),
            ".utilities": ("TestsFlextQualityUtilities", "u"),
            "flext_infra": (
                "check",
                "codegen",
                "codemod",
                "collect_markdown_files",
                "deps",
                "detectors",
                "docs",
                "docs_main",
                "fixers",
                "gates",
                "infra",
                "maintenance",
                "read_ignore_patterns",
                "refactor",
                "release",
                "source_name",
                "transformers",
                "validate",
                "workspace",
                "write_docstring_sources",
                "write_fenced_block_sources",
            ),
            "flext_quality": ("main", "quality"),
            "flext_tests": (
                "api",
                "cli",
                "config",
                "core",
                "d",
                "e",
                "from_json",
                "h",
                "install_local_packages",
                "lazy_attribute",
                "load_infra_report",
                "r",
                "services",
                "settings",
                "td",
                "tf",
                "tk",
                "tm",
                "to_json",
                "to_jsonable_python",
                "tv",
                "x",
            ),
            "flext_web": ("web",),
        }),
        alias_groups=MappingProxyType({}),
        sort_keys=False,
    )
)

install_lazy_exports(__name__, globals(), _LAZY_IMPORTS, public_exports=__all__)
