# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make codegen
#
"""Flext quality package."""

from __future__ import annotations

from typing import TYPE_CHECKING

from flext_core.lazy import cleanup_submodule_namespace, lazy_getattr

if TYPE_CHECKING:
    from flext_cli import d, e, h, r, s, x
    from flext_core.typings import FlextTypes

    from flext_quality import docs, hooks, integrations, mcp, rules, services
    from flext_quality.api import FlextQuality
    from flext_quality.constants import (
        FlextQualityConstants,
        FlextQualityConstants as c,
    )
    from flext_quality.docs import (
        AccessibilityConfig,
        AnalysisDict,
        AuditorResults,
        AuditRules,
        AuditRulesConfig,
        AuditSummary,
        BaseAnalyzer,
        BaseAuditor,
        BaseReporter,
        BaseValidator,
        CompletenessDict,
        Config,
        ConfigDict,
        ConfigManager,
        ContentAnalysisConfig,
        ContentAnalyzer,
        ContentChecksConfig,
        ContentIssue,
        ContentMetrics,
        ContentValidator,
        ContentValidatorResults,
        DocumentationAuditor,
        DocumentationDashboard,
        DocumentationFinder,
        DocumentationNotifier,
        DocumentationOptimizer,
        DocumentationReporter,
        ErrorHandlingConfig,
        FileResults,
        FileStatistics,
        FormattingConfig,
        HeadingsConfig,
        IssueDict,
        LinkChecker,
        LinkCheckResult,
        LinkConfigDict,
        LinkInfoDict,
        LinkInfoDictRequired,
        LinkRecord,
        LinkResultDict,
        LinkResultDictRequired,
        LinkValidationConfig,
        LinkValidator,
        LinkValidatorResults,
        LoggingConfig,
        MaintenanceConfig,
        MarkdownConfig,
        MarkdownStyleConfig,
        MetricsDict,
        NotifierResults,
        OptimizationSummary,
        OptimizerResults,
        PerformanceMetricsDict,
        QualityThresholdsConfig,
        ReadabilityDict,
        Recommendation,
        RecommendationDict,
        ReportData,
        ResultsDict,
        ScheduledMaintenance,
        ScheduleEntry,
        ScheduleResults,
        ScheduleTaskConfig,
        SeverityLevelsConfig,
        StructureDict,
        StyleConfig,
        StyleGuide,
        StyleGuideConfig,
        StyleIssue,
        StyleValidator,
        SummaryMetrics,
        TrendData,
        TrendEntry,
        ValidationConfig,
        ValidationResults,
        ValidationSummary,
        analyze_file_content,
        analyze_files_content,
        core,
        scripts,
        tools,
        validate_file_style,
        validate_files_style,
        validate_links_sync,
    )
    from flext_quality.hooks import BaseHookImpl, HookManager
    from flext_quality.integrations import (
        ExecutionRequest,
        ExecutionResult,
        FlextQualityClaudeContextClient,
        FlextQualityClaudeMemClient,
        FlextQualityCodeExecutionBridge,
        FlextQualityMcpClient,
        McpToolCall,
        McpToolResult,
    )
    from flext_quality.mcp import (
        execute_hook,
        get_hooks_config,
        get_integrations_status,
        get_rules_config,
        get_server,
        search_code,
        search_memory,
        validate_rules,
    )
    from flext_quality.models import FlextQualityModels, FlextQualityModels as m
    from flext_quality.protocols import (
        FlextQualityProtocols,
        FlextQualityProtocols as p,
    )
    from flext_quality.rules import (
        FlextQualityRulesEngine,
        FlextQualityRulesLoader,
        FlextQualityValidators,
    )
    from flext_quality.services import FlextQualityCliService
    from flext_quality.settings import FlextQualitySettings
    from flext_quality.typings import FlextQualityTypes, FlextQualityTypes as t
    from flext_quality.utilities import (
        FlextQualityUtilities,
        FlextQualityUtilities as u,
    )

_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    "AccessibilityConfig": ("flext_quality.docs", "AccessibilityConfig"),
    "AnalysisDict": ("flext_quality.docs", "AnalysisDict"),
    "AuditRules": ("flext_quality.docs", "AuditRules"),
    "AuditRulesConfig": ("flext_quality.docs", "AuditRulesConfig"),
    "AuditSummary": ("flext_quality.docs", "AuditSummary"),
    "AuditorResults": ("flext_quality.docs", "AuditorResults"),
    "BaseAnalyzer": ("flext_quality.docs", "BaseAnalyzer"),
    "BaseAuditor": ("flext_quality.docs", "BaseAuditor"),
    "BaseHookImpl": ("flext_quality.hooks", "BaseHookImpl"),
    "BaseReporter": ("flext_quality.docs", "BaseReporter"),
    "BaseValidator": ("flext_quality.docs", "BaseValidator"),
    "CompletenessDict": ("flext_quality.docs", "CompletenessDict"),
    "Config": ("flext_quality.docs", "Config"),
    "ConfigDict": ("flext_quality.docs", "ConfigDict"),
    "ConfigManager": ("flext_quality.docs", "ConfigManager"),
    "ContentAnalysisConfig": ("flext_quality.docs", "ContentAnalysisConfig"),
    "ContentAnalyzer": ("flext_quality.docs", "ContentAnalyzer"),
    "ContentChecksConfig": ("flext_quality.docs", "ContentChecksConfig"),
    "ContentIssue": ("flext_quality.docs", "ContentIssue"),
    "ContentMetrics": ("flext_quality.docs", "ContentMetrics"),
    "ContentValidator": ("flext_quality.docs", "ContentValidator"),
    "ContentValidatorResults": ("flext_quality.docs", "ContentValidatorResults"),
    "DocumentationAuditor": ("flext_quality.docs", "DocumentationAuditor"),
    "DocumentationDashboard": ("flext_quality.docs", "DocumentationDashboard"),
    "DocumentationFinder": ("flext_quality.docs", "DocumentationFinder"),
    "DocumentationNotifier": ("flext_quality.docs", "DocumentationNotifier"),
    "DocumentationOptimizer": ("flext_quality.docs", "DocumentationOptimizer"),
    "DocumentationReporter": ("flext_quality.docs", "DocumentationReporter"),
    "ErrorHandlingConfig": ("flext_quality.docs", "ErrorHandlingConfig"),
    "ExecutionRequest": ("flext_quality.integrations", "ExecutionRequest"),
    "ExecutionResult": ("flext_quality.integrations", "ExecutionResult"),
    "FileResults": ("flext_quality.docs", "FileResults"),
    "FileStatistics": ("flext_quality.docs", "FileStatistics"),
    "FlextQuality": ("flext_quality.api", "FlextQuality"),
    "FlextQualityClaudeContextClient": (
        "flext_quality.integrations",
        "FlextQualityClaudeContextClient",
    ),
    "FlextQualityClaudeMemClient": (
        "flext_quality.integrations",
        "FlextQualityClaudeMemClient",
    ),
    "FlextQualityCliService": ("flext_quality.services", "FlextQualityCliService"),
    "FlextQualityCodeExecutionBridge": (
        "flext_quality.integrations",
        "FlextQualityCodeExecutionBridge",
    ),
    "FlextQualityConstants": ("flext_quality.constants", "FlextQualityConstants"),
    "FlextQualityMcpClient": ("flext_quality.integrations", "FlextQualityMcpClient"),
    "FlextQualityModels": ("flext_quality.models", "FlextQualityModels"),
    "FlextQualityProtocols": ("flext_quality.protocols", "FlextQualityProtocols"),
    "FlextQualityRulesEngine": ("flext_quality.rules", "FlextQualityRulesEngine"),
    "FlextQualityRulesLoader": ("flext_quality.rules", "FlextQualityRulesLoader"),
    "FlextQualitySettings": ("flext_quality.settings", "FlextQualitySettings"),
    "FlextQualityTypes": ("flext_quality.typings", "FlextQualityTypes"),
    "FlextQualityUtilities": ("flext_quality.utilities", "FlextQualityUtilities"),
    "FlextQualityValidators": ("flext_quality.rules", "FlextQualityValidators"),
    "FormattingConfig": ("flext_quality.docs", "FormattingConfig"),
    "HeadingsConfig": ("flext_quality.docs", "HeadingsConfig"),
    "HookManager": ("flext_quality.hooks", "HookManager"),
    "IssueDict": ("flext_quality.docs", "IssueDict"),
    "LinkCheckResult": ("flext_quality.docs", "LinkCheckResult"),
    "LinkChecker": ("flext_quality.docs", "LinkChecker"),
    "LinkConfigDict": ("flext_quality.docs", "LinkConfigDict"),
    "LinkInfoDict": ("flext_quality.docs", "LinkInfoDict"),
    "LinkInfoDictRequired": ("flext_quality.docs", "LinkInfoDictRequired"),
    "LinkRecord": ("flext_quality.docs", "LinkRecord"),
    "LinkResultDict": ("flext_quality.docs", "LinkResultDict"),
    "LinkResultDictRequired": ("flext_quality.docs", "LinkResultDictRequired"),
    "LinkValidationConfig": ("flext_quality.docs", "LinkValidationConfig"),
    "LinkValidator": ("flext_quality.docs", "LinkValidator"),
    "LinkValidatorResults": ("flext_quality.docs", "LinkValidatorResults"),
    "LoggingConfig": ("flext_quality.docs", "LoggingConfig"),
    "MaintenanceConfig": ("flext_quality.docs", "MaintenanceConfig"),
    "MarkdownConfig": ("flext_quality.docs", "MarkdownConfig"),
    "MarkdownStyleConfig": ("flext_quality.docs", "MarkdownStyleConfig"),
    "McpToolCall": ("flext_quality.integrations", "McpToolCall"),
    "McpToolResult": ("flext_quality.integrations", "McpToolResult"),
    "MetricsDict": ("flext_quality.docs", "MetricsDict"),
    "NotifierResults": ("flext_quality.docs", "NotifierResults"),
    "OptimizationSummary": ("flext_quality.docs", "OptimizationSummary"),
    "OptimizerResults": ("flext_quality.docs", "OptimizerResults"),
    "PerformanceMetricsDict": ("flext_quality.docs", "PerformanceMetricsDict"),
    "QualityThresholdsConfig": ("flext_quality.docs", "QualityThresholdsConfig"),
    "ReadabilityDict": ("flext_quality.docs", "ReadabilityDict"),
    "Recommendation": ("flext_quality.docs", "Recommendation"),
    "RecommendationDict": ("flext_quality.docs", "RecommendationDict"),
    "ReportData": ("flext_quality.docs", "ReportData"),
    "ResultsDict": ("flext_quality.docs", "ResultsDict"),
    "ScheduleEntry": ("flext_quality.docs", "ScheduleEntry"),
    "ScheduleResults": ("flext_quality.docs", "ScheduleResults"),
    "ScheduleTaskConfig": ("flext_quality.docs", "ScheduleTaskConfig"),
    "ScheduledMaintenance": ("flext_quality.docs", "ScheduledMaintenance"),
    "SeverityLevelsConfig": ("flext_quality.docs", "SeverityLevelsConfig"),
    "StructureDict": ("flext_quality.docs", "StructureDict"),
    "StyleConfig": ("flext_quality.docs", "StyleConfig"),
    "StyleGuide": ("flext_quality.docs", "StyleGuide"),
    "StyleGuideConfig": ("flext_quality.docs", "StyleGuideConfig"),
    "StyleIssue": ("flext_quality.docs", "StyleIssue"),
    "StyleValidator": ("flext_quality.docs", "StyleValidator"),
    "SummaryMetrics": ("flext_quality.docs", "SummaryMetrics"),
    "TrendData": ("flext_quality.docs", "TrendData"),
    "TrendEntry": ("flext_quality.docs", "TrendEntry"),
    "ValidationConfig": ("flext_quality.docs", "ValidationConfig"),
    "ValidationResults": ("flext_quality.docs", "ValidationResults"),
    "ValidationSummary": ("flext_quality.docs", "ValidationSummary"),
    "analyze_file_content": ("flext_quality.docs", "analyze_file_content"),
    "analyze_files_content": ("flext_quality.docs", "analyze_files_content"),
    "c": ("flext_quality.constants", "FlextQualityConstants"),
    "core": ("flext_quality.docs", "core"),
    "d": ("flext_cli", "d"),
    "docs": ("flext_quality.docs", ""),
    "e": ("flext_cli", "e"),
    "execute_hook": ("flext_quality.mcp", "execute_hook"),
    "get_hooks_config": ("flext_quality.mcp", "get_hooks_config"),
    "get_integrations_status": ("flext_quality.mcp", "get_integrations_status"),
    "get_rules_config": ("flext_quality.mcp", "get_rules_config"),
    "get_server": ("flext_quality.mcp", "get_server"),
    "h": ("flext_cli", "h"),
    "hooks": ("flext_quality.hooks", ""),
    "integrations": ("flext_quality.integrations", ""),
    "m": ("flext_quality.models", "FlextQualityModels"),
    "mcp": ("flext_quality.mcp", ""),
    "p": ("flext_quality.protocols", "FlextQualityProtocols"),
    "r": ("flext_cli", "r"),
    "rules": ("flext_quality.rules", ""),
    "s": ("flext_cli", "s"),
    "scripts": ("flext_quality.docs", "scripts"),
    "search_code": ("flext_quality.mcp", "search_code"),
    "search_memory": ("flext_quality.mcp", "search_memory"),
    "services": ("flext_quality.services", ""),
    "t": ("flext_quality.typings", "FlextQualityTypes"),
    "tools": ("flext_quality.docs", "tools"),
    "u": ("flext_quality.utilities", "FlextQualityUtilities"),
    "validate_file_style": ("flext_quality.docs", "validate_file_style"),
    "validate_files_style": ("flext_quality.docs", "validate_files_style"),
    "validate_links_sync": ("flext_quality.docs", "validate_links_sync"),
    "validate_rules": ("flext_quality.mcp", "validate_rules"),
    "x": ("flext_cli", "x"),
}

__all__ = [
    "AccessibilityConfig",
    "AnalysisDict",
    "AuditRules",
    "AuditRulesConfig",
    "AuditSummary",
    "AuditorResults",
    "BaseAnalyzer",
    "BaseAuditor",
    "BaseHookImpl",
    "BaseReporter",
    "BaseValidator",
    "CompletenessDict",
    "Config",
    "ConfigDict",
    "ConfigManager",
    "ContentAnalysisConfig",
    "ContentAnalyzer",
    "ContentChecksConfig",
    "ContentIssue",
    "ContentMetrics",
    "ContentValidator",
    "ContentValidatorResults",
    "DocumentationAuditor",
    "DocumentationDashboard",
    "DocumentationFinder",
    "DocumentationNotifier",
    "DocumentationOptimizer",
    "DocumentationReporter",
    "ErrorHandlingConfig",
    "ExecutionRequest",
    "ExecutionResult",
    "FileResults",
    "FileStatistics",
    "FlextQuality",
    "FlextQualityClaudeContextClient",
    "FlextQualityClaudeMemClient",
    "FlextQualityCliService",
    "FlextQualityCodeExecutionBridge",
    "FlextQualityConstants",
    "FlextQualityMcpClient",
    "FlextQualityModels",
    "FlextQualityProtocols",
    "FlextQualityRulesEngine",
    "FlextQualityRulesLoader",
    "FlextQualitySettings",
    "FlextQualityTypes",
    "FlextQualityUtilities",
    "FlextQualityValidators",
    "FormattingConfig",
    "HeadingsConfig",
    "HookManager",
    "IssueDict",
    "LinkCheckResult",
    "LinkChecker",
    "LinkConfigDict",
    "LinkInfoDict",
    "LinkInfoDictRequired",
    "LinkRecord",
    "LinkResultDict",
    "LinkResultDictRequired",
    "LinkValidationConfig",
    "LinkValidator",
    "LinkValidatorResults",
    "LoggingConfig",
    "MaintenanceConfig",
    "MarkdownConfig",
    "MarkdownStyleConfig",
    "McpToolCall",
    "McpToolResult",
    "MetricsDict",
    "NotifierResults",
    "OptimizationSummary",
    "OptimizerResults",
    "PerformanceMetricsDict",
    "QualityThresholdsConfig",
    "ReadabilityDict",
    "Recommendation",
    "RecommendationDict",
    "ReportData",
    "ResultsDict",
    "ScheduleEntry",
    "ScheduleResults",
    "ScheduleTaskConfig",
    "ScheduledMaintenance",
    "SeverityLevelsConfig",
    "StructureDict",
    "StyleConfig",
    "StyleGuide",
    "StyleGuideConfig",
    "StyleIssue",
    "StyleValidator",
    "SummaryMetrics",
    "TrendData",
    "TrendEntry",
    "ValidationConfig",
    "ValidationResults",
    "ValidationSummary",
    "analyze_file_content",
    "analyze_files_content",
    "c",
    "core",
    "d",
    "docs",
    "e",
    "execute_hook",
    "get_hooks_config",
    "get_integrations_status",
    "get_rules_config",
    "get_server",
    "h",
    "hooks",
    "integrations",
    "m",
    "mcp",
    "p",
    "r",
    "rules",
    "s",
    "scripts",
    "search_code",
    "search_memory",
    "services",
    "t",
    "tools",
    "u",
    "validate_file_style",
    "validate_files_style",
    "validate_links_sync",
    "validate_rules",
    "x",
]


def __getattr__(name: str) -> FlextTypes.ModuleExport:
    """Lazy-load module attributes on first access (PEP 562)."""
    return lazy_getattr(name, _LAZY_IMPORTS, globals(), __name__)


def __dir__() -> list[str]:
    """Return list of available attributes for dir() and autocomplete."""
    return sorted(__all__)


cleanup_submodule_namespace(__name__, _LAZY_IMPORTS)
