# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make codegen
#
"""FLEXT Quality Documentation Maintenance Package.

This package contains tools and utilities for maintaining documentation quality
across the FLEXT workspace, including auditing, validation, and reporting.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from flext_core.lazy import cleanup_submodule_namespace, lazy_getattr

if TYPE_CHECKING:
    from flext_core.typings import FlextTypes

    from flext_quality.docs import core, scripts, tools
    from flext_quality.docs.core import (
        AuditRules,
        BaseAnalyzer,
        BaseAuditor,
        BaseReporter,
        BaseValidator,
        Config,
        ConfigManager,
        DocumentationFinder,
        FileStatistics,
        StyleGuide,
        ValidationConfig,
    )
    from flext_quality.docs.dashboard import DocumentationDashboard
    from flext_quality.docs.notifications import (
        MAX_BROKEN_LINKS_TO_SHOW,
        DocumentationNotifier,
        NotifierResults,
    )
    from flext_quality.docs.scheduled_maintenance import (
        ErrorHandlingConfig,
        LoggingConfig,
        MaintenanceConfig,
        ScheduledMaintenance,
        ScheduleEntry,
        ScheduleResults,
        ScheduleTaskConfig,
        main,
    )
    from flext_quality.docs.scripts import (
        AccessibilityConfig,
        AuditorResults,
        AuditRulesConfig,
        AuditSummary,
        ContentAnalysisConfig,
        ContentChecksConfig,
        ContentIssue,
        ContentMetrics,
        ContentValidator,
        ContentValidatorResults,
        DocumentationAuditor,
        DocumentationOptimizer,
        DocumentationReporter,
        FormattingConfig,
        LinkCheckResult,
        LinkRecord,
        LinkValidationConfig,
        LinkValidator,
        LinkValidatorResults,
        MarkdownStyleConfig,
        MetricsDict,
        OptimizationSummary,
        OptimizerResults,
        QualityThresholdsConfig,
        Recommendation,
        ReportData,
        SeverityLevelsConfig,
        StyleGuideConfig,
        SummaryMetrics,
        TrendData,
        TrendEntry,
        ValidationSummary,
    )
    from flext_quality.docs.tools import (
        AnalysisDict,
        CompletenessDict,
        ConfigDict,
        ContentAnalyzer,
        FileResults,
        HeadingsConfig,
        IssueDict,
        LinkChecker,
        LinkConfigDict,
        LinkInfoDict,
        LinkInfoDictRequired,
        LinkResultDict,
        LinkResultDictRequired,
        MarkdownConfig,
        PerformanceMetricsDict,
        ReadabilityDict,
        RecommendationDict,
        ResultsDict,
        StructureDict,
        StyleConfig,
        StyleIssue,
        StyleValidator,
        ValidationResults,
        analyze_file_content,
        analyze_files_content,
        validate_file_style,
        validate_files_style,
        validate_links_sync,
    )

_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    "AccessibilityConfig": ("flext_quality.docs.scripts", "AccessibilityConfig"),
    "AnalysisDict": ("flext_quality.docs.tools", "AnalysisDict"),
    "AuditRules": ("flext_quality.docs.core", "AuditRules"),
    "AuditRulesConfig": ("flext_quality.docs.scripts", "AuditRulesConfig"),
    "AuditSummary": ("flext_quality.docs.scripts", "AuditSummary"),
    "AuditorResults": ("flext_quality.docs.scripts", "AuditorResults"),
    "BaseAnalyzer": ("flext_quality.docs.core", "BaseAnalyzer"),
    "BaseAuditor": ("flext_quality.docs.core", "BaseAuditor"),
    "BaseReporter": ("flext_quality.docs.core", "BaseReporter"),
    "BaseValidator": ("flext_quality.docs.core", "BaseValidator"),
    "CompletenessDict": ("flext_quality.docs.tools", "CompletenessDict"),
    "Config": ("flext_quality.docs.core", "Config"),
    "ConfigDict": ("flext_quality.docs.tools", "ConfigDict"),
    "ConfigManager": ("flext_quality.docs.core", "ConfigManager"),
    "ContentAnalysisConfig": ("flext_quality.docs.scripts", "ContentAnalysisConfig"),
    "ContentAnalyzer": ("flext_quality.docs.tools", "ContentAnalyzer"),
    "ContentChecksConfig": ("flext_quality.docs.scripts", "ContentChecksConfig"),
    "ContentIssue": ("flext_quality.docs.scripts", "ContentIssue"),
    "ContentMetrics": ("flext_quality.docs.scripts", "ContentMetrics"),
    "ContentValidator": ("flext_quality.docs.scripts", "ContentValidator"),
    "ContentValidatorResults": (
        "flext_quality.docs.scripts",
        "ContentValidatorResults",
    ),
    "DocumentationAuditor": ("flext_quality.docs.scripts", "DocumentationAuditor"),
    "DocumentationDashboard": (
        "flext_quality.docs.dashboard",
        "DocumentationDashboard",
    ),
    "DocumentationFinder": ("flext_quality.docs.core", "DocumentationFinder"),
    "DocumentationNotifier": (
        "flext_quality.docs.notifications",
        "DocumentationNotifier",
    ),
    "DocumentationOptimizer": ("flext_quality.docs.scripts", "DocumentationOptimizer"),
    "DocumentationReporter": ("flext_quality.docs.scripts", "DocumentationReporter"),
    "ErrorHandlingConfig": (
        "flext_quality.docs.scheduled_maintenance",
        "ErrorHandlingConfig",
    ),
    "FileResults": ("flext_quality.docs.tools", "FileResults"),
    "FileStatistics": ("flext_quality.docs.core", "FileStatistics"),
    "FormattingConfig": ("flext_quality.docs.scripts", "FormattingConfig"),
    "HeadingsConfig": ("flext_quality.docs.tools", "HeadingsConfig"),
    "IssueDict": ("flext_quality.docs.tools", "IssueDict"),
    "LinkCheckResult": ("flext_quality.docs.scripts", "LinkCheckResult"),
    "LinkChecker": ("flext_quality.docs.tools", "LinkChecker"),
    "LinkConfigDict": ("flext_quality.docs.tools", "LinkConfigDict"),
    "LinkInfoDict": ("flext_quality.docs.tools", "LinkInfoDict"),
    "LinkInfoDictRequired": ("flext_quality.docs.tools", "LinkInfoDictRequired"),
    "LinkRecord": ("flext_quality.docs.scripts", "LinkRecord"),
    "LinkResultDict": ("flext_quality.docs.tools", "LinkResultDict"),
    "LinkResultDictRequired": ("flext_quality.docs.tools", "LinkResultDictRequired"),
    "LinkValidationConfig": ("flext_quality.docs.scripts", "LinkValidationConfig"),
    "LinkValidator": ("flext_quality.docs.scripts", "LinkValidator"),
    "LinkValidatorResults": ("flext_quality.docs.scripts", "LinkValidatorResults"),
    "LoggingConfig": ("flext_quality.docs.scheduled_maintenance", "LoggingConfig"),
    "MAX_BROKEN_LINKS_TO_SHOW": (
        "flext_quality.docs.notifications",
        "MAX_BROKEN_LINKS_TO_SHOW",
    ),
    "MaintenanceConfig": (
        "flext_quality.docs.scheduled_maintenance",
        "MaintenanceConfig",
    ),
    "MarkdownConfig": ("flext_quality.docs.tools", "MarkdownConfig"),
    "MarkdownStyleConfig": ("flext_quality.docs.scripts", "MarkdownStyleConfig"),
    "MetricsDict": ("flext_quality.docs.scripts", "MetricsDict"),
    "NotifierResults": ("flext_quality.docs.notifications", "NotifierResults"),
    "OptimizationSummary": ("flext_quality.docs.scripts", "OptimizationSummary"),
    "OptimizerResults": ("flext_quality.docs.scripts", "OptimizerResults"),
    "PerformanceMetricsDict": ("flext_quality.docs.tools", "PerformanceMetricsDict"),
    "QualityThresholdsConfig": (
        "flext_quality.docs.scripts",
        "QualityThresholdsConfig",
    ),
    "ReadabilityDict": ("flext_quality.docs.tools", "ReadabilityDict"),
    "Recommendation": ("flext_quality.docs.scripts", "Recommendation"),
    "RecommendationDict": ("flext_quality.docs.tools", "RecommendationDict"),
    "ReportData": ("flext_quality.docs.scripts", "ReportData"),
    "ResultsDict": ("flext_quality.docs.tools", "ResultsDict"),
    "ScheduleEntry": ("flext_quality.docs.scheduled_maintenance", "ScheduleEntry"),
    "ScheduleResults": ("flext_quality.docs.scheduled_maintenance", "ScheduleResults"),
    "ScheduleTaskConfig": (
        "flext_quality.docs.scheduled_maintenance",
        "ScheduleTaskConfig",
    ),
    "ScheduledMaintenance": (
        "flext_quality.docs.scheduled_maintenance",
        "ScheduledMaintenance",
    ),
    "SeverityLevelsConfig": ("flext_quality.docs.scripts", "SeverityLevelsConfig"),
    "StructureDict": ("flext_quality.docs.tools", "StructureDict"),
    "StyleConfig": ("flext_quality.docs.tools", "StyleConfig"),
    "StyleGuide": ("flext_quality.docs.core", "StyleGuide"),
    "StyleGuideConfig": ("flext_quality.docs.scripts", "StyleGuideConfig"),
    "StyleIssue": ("flext_quality.docs.tools", "StyleIssue"),
    "StyleValidator": ("flext_quality.docs.tools", "StyleValidator"),
    "SummaryMetrics": ("flext_quality.docs.scripts", "SummaryMetrics"),
    "TrendData": ("flext_quality.docs.scripts", "TrendData"),
    "TrendEntry": ("flext_quality.docs.scripts", "TrendEntry"),
    "ValidationConfig": ("flext_quality.docs.core", "ValidationConfig"),
    "ValidationResults": ("flext_quality.docs.tools", "ValidationResults"),
    "ValidationSummary": ("flext_quality.docs.scripts", "ValidationSummary"),
    "analyze_file_content": ("flext_quality.docs.tools", "analyze_file_content"),
    "analyze_files_content": ("flext_quality.docs.tools", "analyze_files_content"),
    "core": ("flext_quality.docs.core", ""),
    "main": ("flext_quality.docs.scheduled_maintenance", "main"),
    "scripts": ("flext_quality.docs.scripts", ""),
    "tools": ("flext_quality.docs.tools", ""),
    "validate_file_style": ("flext_quality.docs.tools", "validate_file_style"),
    "validate_files_style": ("flext_quality.docs.tools", "validate_files_style"),
    "validate_links_sync": ("flext_quality.docs.tools", "validate_links_sync"),
}

__all__ = [
    "MAX_BROKEN_LINKS_TO_SHOW",
    "AccessibilityConfig",
    "AnalysisDict",
    "AuditRules",
    "AuditRulesConfig",
    "AuditSummary",
    "AuditorResults",
    "BaseAnalyzer",
    "BaseAuditor",
    "BaseReporter",
    "BaseValidator",
    "CompletenessDict",
    "Config",
    "ConfigDict",
    "ConfigManager",
    "ContentAnalysisConfig",
    "ContentAnalyzer",
    "ContentChecksConfig",
    "ContentIssue",
    "ContentMetrics",
    "ContentValidator",
    "ContentValidatorResults",
    "DocumentationAuditor",
    "DocumentationDashboard",
    "DocumentationFinder",
    "DocumentationNotifier",
    "DocumentationOptimizer",
    "DocumentationReporter",
    "ErrorHandlingConfig",
    "FileResults",
    "FileStatistics",
    "FormattingConfig",
    "HeadingsConfig",
    "IssueDict",
    "LinkCheckResult",
    "LinkChecker",
    "LinkConfigDict",
    "LinkInfoDict",
    "LinkInfoDictRequired",
    "LinkRecord",
    "LinkResultDict",
    "LinkResultDictRequired",
    "LinkValidationConfig",
    "LinkValidator",
    "LinkValidatorResults",
    "LoggingConfig",
    "MaintenanceConfig",
    "MarkdownConfig",
    "MarkdownStyleConfig",
    "MetricsDict",
    "NotifierResults",
    "OptimizationSummary",
    "OptimizerResults",
    "PerformanceMetricsDict",
    "QualityThresholdsConfig",
    "ReadabilityDict",
    "Recommendation",
    "RecommendationDict",
    "ReportData",
    "ResultsDict",
    "ScheduleEntry",
    "ScheduleResults",
    "ScheduleTaskConfig",
    "ScheduledMaintenance",
    "SeverityLevelsConfig",
    "StructureDict",
    "StyleConfig",
    "StyleGuide",
    "StyleGuideConfig",
    "StyleIssue",
    "StyleValidator",
    "SummaryMetrics",
    "TrendData",
    "TrendEntry",
    "ValidationConfig",
    "ValidationResults",
    "ValidationSummary",
    "analyze_file_content",
    "analyze_files_content",
    "core",
    "main",
    "scripts",
    "tools",
    "validate_file_style",
    "validate_files_style",
    "validate_links_sync",
]


def __getattr__(name: str) -> FlextTypes.ModuleExport:
    """Lazy-load module attributes on first access (PEP 562)."""
    return lazy_getattr(name, _LAZY_IMPORTS, globals(), __name__)


def __dir__() -> list[str]:
    """Return list of available attributes for dir() and autocomplete."""
    return sorted(__all__)


cleanup_submodule_namespace(__name__, _LAZY_IMPORTS)
