from pydantic import Field
from typing import List
from pathlib import Path
"""Module 0001_initial.

# Generated by Django 4.2.22 on 2025-06-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """TODO: Add docstring."""

    initial = True

    dependencies: list = {}

    operations = [
        migrations.CreateModel(
            name="AnalysisBackendModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("version", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=False)),
                ("capabilities", models.JSONField(default=list)),
                ("default_enabled", models.BooleanField(default=True)),
                ("execution_order", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "analyzer_backend",
                "ordering": ["execution_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Analysis Session", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("include_security", models.BooleanField(default=True)),
                ("include_dead_code", models.BooleanField(default=True)),
                ("include_duplicates", models.BooleanField(default=True)),
                ("complexity_threshold", models.FloatField(default=10.0)),
                ("similarity_threshold", models.FloatField(default=0.8)),
                (
                    "backends_used",
                    models.JSONField(
                        default=list,
                        help_text="List of analysis backends used",
                    ),
                ),
                ("overall_score", models.FloatField(blank=True, null=True)),
                (
                    "quality_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("C-", "C-"),
                            ("D+", "D+"),
                            ("D", "D"),
                            ("F", "F"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("files_analyzed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "analyzer_analysis_session",
            },
        ),
        migrations.CreateModel(
            name="ClassAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("full_name", models.CharField(max_length=500)),
                ("line_start", models.IntegerField()),
                ("line_end", models.IntegerField()),
                ("lines_of_code", models.IntegerField(default=0)),
                ("method_count", models.IntegerField(default=0)),
                ("property_count", models.IntegerField(default=0)),
                ("class_method_count", models.IntegerField(default=0)),
                ("static_method_count", models.IntegerField(default=0)),
                ("base_classes", models.JSONField(default=list)),
                ("inheritance_depth", models.IntegerField(default=0)),
                ("complexity_score", models.FloatField(default=0.0)),
                (
                    "complexity_level",
                    models.CharField(
                        choices=[
                            ("low", "Low (1-5)"),
                            ("medium", "Medium (6-10)"),
                            ("high", "High (11-20)"),
                            ("very_high", "Very High (21+)"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("has_docstring", models.BooleanField(default=False)),
                ("docstring_length", models.IntegerField(default=0)),
                ("is_abstract", models.BooleanField(default=False)),
                ("is_singleton", models.BooleanField(default=False)),
                ("is_dataclass", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analyzer_class_analysis",
            },
        ),
        migrations.CreateModel(
            name="DuplicateCodeBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_hash", models.CharField(max_length=64, unique=True)),
                ("lines_count", models.IntegerField()),
                ("similarity_score", models.FloatField()),
                ("content_preview", models.TextField()),
                ("is_refactored", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_blocks",
                        to="analyzer.analysissession",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_duplicate_code_block",
            },
        ),
        migrations.CreateModel(
            name="FileAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_name", models.CharField(max_length=255)),
                ("lines_of_code", models.IntegerField()),
                ("comment_lines", models.IntegerField()),
                ("blank_lines", models.IntegerField()),
                ("complexity_score", models.FloatField()),
                ("maintainability_score", models.FloatField()),
                ("function_count", models.IntegerField()),
                ("class_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_analyses",
                        to="analyzer.analysissession",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_file_analysis",
            },
        ),
        migrations.CreateModel(
            name="FunctionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("full_name", models.CharField(max_length=500)),
                (
                    "function_type",
                    models.CharField(
                        choices=[
                            ("function", "Function"),
                            ("method", "Method"),
                            ("classmethod", "Class Method"),
                            ("staticmethod", "Static Method"),
                            ("property", "Property"),
                            ("async_function", "Async Function"),
                            ("async_method", "Async Method"),
                        ],
                        default="function",
                        max_length=20,
                    ),
                ),
                ("line_start", models.IntegerField()),
                ("line_end", models.IntegerField()),
                ("lines_of_code", models.IntegerField(default=0)),
                ("parameter_count", models.IntegerField(default=0)),
                ("return_statement_count", models.IntegerField(default=0)),
                ("cyclomatic_complexity", models.IntegerField(default=1)),
                ("cognitive_complexity", models.IntegerField(default=0)),
                (
                    "complexity_level",
                    models.CharField(
                        choices=[
                            ("low", "Low (1-5)"),
                            ("medium", "Medium (6-10)"),
                            ("high", "High (11-20)"),
                            ("very_high", "Very High (21+)"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("has_docstring", models.BooleanField(default=False)),
                ("has_type_hints", models.BooleanField(default=False)),
                ("docstring_length", models.IntegerField(default=0)),
                ("has_too_many_parameters", models.BooleanField(default=False)),
                ("has_long_parameter_list", models.BooleanField(default=False)),
                ("is_too_long", models.BooleanField(default=False)),
                ("parameters", models.JSONField(default=list)),
                ("return_type", models.CharField(blank=True, max_length=100)),
                ("decorators", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="analyzer.classanalysis",
                    ),
                ),
                (
                    "file_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="function_analyses",
                        to="analyzer.fileanalysis",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_function_analysis",
            },
        ),
        migrations.CreateModel(
            name="PackageAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("full_path", models.CharField(max_length=500)),
                ("is_namespace", models.BooleanField(default=False)),
                ("total_files", models.IntegerField(default=0)),
                ("python_files_count", models.IntegerField(default=0)),
                ("total_lines", models.IntegerField(default=0)),
                ("code_lines", models.IntegerField(default=0)),
                ("comment_lines", models.IntegerField(default=0)),
                ("blank_lines", models.IntegerField(default=0)),
                ("avg_complexity", models.FloatField(default=0.0)),
                ("max_complexity", models.FloatField(default=0.0)),
                ("total_functions", models.IntegerField(default=0)),
                ("total_classes", models.IntegerField(default=0)),
                ("total_methods", models.IntegerField(default=0)),
                ("maintainability_score", models.FloatField(default=0.0)),
                ("test_coverage", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_analyses",
                        to="analyzer.analysissession",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_package_analysis",
            },
        ),
        migrations.CreateModel(
            name="VariableAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("full_name", models.CharField(max_length=500)),
                (
                    "variable_type",
                    models.CharField(
                        choices=[
                            ("constant", "Constant"),
                            ("global_var", "Global Variable"),
                            ("class_var", "Class Variable"),
                            ("instance_var", "Instance Variable"),
                            ("local_var", "Local Variable"),
                            ("parameter", "Parameter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("module", "Module Level"),
                            ("class", "Class Level"),
                            ("function", "Function Level"),
                        ],
                        max_length=20,
                    ),
                ),
                ("line_number", models.IntegerField()),
                ("inferred_type", models.CharField(blank=True, max_length=100)),
                ("has_type_annotation", models.BooleanField(default=False)),
                ("type_annotation", models.CharField(blank=True, max_length=200)),
                ("is_constant", models.BooleanField(default=False)),
                ("initial_value", models.TextField(blank=True)),
                ("is_unused", models.BooleanField(default=False)),
                ("follows_naming_convention", models.BooleanField(default=True)),
                ("naming_issue", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="analyzer.classanalysis",
                    ),
                ),
                (
                    "file_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variable_analyses",
                        to="analyzer.fileanalysis",
                    ),
                ),
                (
                    "function_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="analyzer.functionanalysis",
                    ),
                ),
                (
                    "package_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="analyzer.packageanalysis",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_variable_analysis",
            },
        ),
        migrations.CreateModel(
            name="SecurityIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("issue_type", models.CharField(max_length=100)),
                ("test_id", models.CharField(max_length=50)),
                ("file_path", models.CharField(max_length=500)),
                ("line_number", models.IntegerField()),
                ("description", models.TextField()),
                ("recommendation", models.TextField()),
                ("code_snippet", models.TextField(blank=True)),
                ("is_fixed", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_issues",
                        to="analyzer.analysissession",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_security_issue",
            },
        ),
        migrations.CreateModel(
            name="QualityMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.FloatField()),
                ("complexity_score", models.FloatField()),
                ("maintainability_score", models.FloatField()),
                ("security_score", models.FloatField()),
                ("documentation_score", models.FloatField()),
                ("duplication_score", models.FloatField()),
                ("total_files", models.IntegerField()),
                ("total_lines", models.IntegerField()),
                ("total_functions", models.IntegerField()),
                ("total_classes", models.IntegerField()),
                ("avg_complexity", models.FloatField()),
                ("max_complexity", models.FloatField()),
                ("complex_functions_count", models.IntegerField()),
                ("docstring_coverage", models.FloatField()),
                ("documented_functions", models.IntegerField()),
                ("security_issues_count", models.IntegerField()),
                ("dead_code_items_count", models.IntegerField()),
                ("duplicate_blocks_count", models.IntegerField()),
                ("duplicate_lines_ratio", models.FloatField()),
                ("technical_debt_ratio", models.FloatField()),
                ("estimated_debt_hours", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_metrics",
                        to="analyzer.analysissession",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_quality_metrics",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "path",
                    models.CharField(
                        help_text="Path to the flx_project directory",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "package_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_installed_package", models.BooleanField(default=False)),
                (
                    "install_location",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "package_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("source", "Source Installation"),
                            ("wheel", "Wheel Package"),
                            ("system", "System Package"),
                            ("local", "Local Package"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("total_files", models.IntegerField(default=0)),
                ("total_lines", models.IntegerField(default=0)),
                ("python_files", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "analyzer_project",
                "indexes": [
                    models.Index(
                        fields=["created_at"],
                        name="analyzer_pr_created_482c88_idx",
                    ),
                    models.Index(
                        fields=["package_name"],
                        name="analyzer_pr_package_9e3f34_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IssueType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("quality", "Code Quality"),
                            ("complexity", "Complexity"),
                            ("dead_code", "Dead Code"),
                            ("style", "Code Style"),
                            ("documentation", "Documentation"),
                            ("performance", "Performance"),
                            ("maintainability", "Maintainability"),
                            ("best_practices", "Best Practices"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("recommendation", models.TextField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                ("examples", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_types",
                        to="analyzer.analysisbackendmodel",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_issue_type",
            },
        ),
        migrations.CreateModel(
            name="ImportAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=200)),
                ("import_name", models.CharField(blank=True, max_length=200)),
                ("alias", models.CharField(blank=True, max_length=200)),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Library"),
                            ("third_party", "Third Party"),
                            ("local", "Local/Project"),
                            ("relative", "Relative Import"),
                        ],
                        max_length=20,
                    ),
                ),
                ("line_number", models.IntegerField()),
                ("is_wildcard", models.BooleanField(default=False)),
                ("is_unused", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("is_circular", models.BooleanField(default=False)),
                ("is_deprecated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_analyses",
                        to="analyzer.fileanalysis",
                    ),
                ),
                (
                    "package_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="analyzer.packageanalysis",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_import_analysis",
            },
        ),
        migrations.AddField(
            model_name="functionanalysis",
            name="package_analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="functions",
                to="analyzer.packageanalysis",
            ),
        ),
        migrations.CreateModel(
            name="DuplicateLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("start_line", models.IntegerField()),
                ("end_line", models.IntegerField()),
                (
                    "duplicate_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="analyzer.duplicatecodeblock",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_duplicate_location",
            },
        ),
        migrations.CreateModel(
            name="DetectedIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("line_number", models.IntegerField()),
                ("column", models.IntegerField(default=0)),
                ("message", models.TextField()),
                ("code_snippet", models.TextField(blank=True)),
                ("context", models.JSONField(default=dict)),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("raw_data", models.JSONField(default=dict)),
                ("is_false_positive", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_issues",
                        to="analyzer.fileanalysis",
                    ),
                ),
                (
                    "issue_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="analyzer.issuetype",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_issues",
                        to="analyzer.analysissession",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_detected_issue",
            },
        ),
        migrations.CreateModel(
            name="DeadCodeIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dead_type",
                    models.CharField(
                        choices=[
                            ("function", "Unused Function"),
                            ("variable", "Unused Variable"),
                            ("import", "Unused Import"),
                            ("class", "Unused Class"),
                            ("unreachable", "Unreachable Code"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file_path", models.CharField(max_length=500)),
                ("line_number", models.IntegerField()),
                ("confidence", models.FloatField()),
                (
                    "size_estimate",
                    models.IntegerField(
                        help_text="Lines of code that could be removed",
                    ),
                ),
                ("is_fixed", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dead_code_issues",
                        to="analyzer.analysissession",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_dead_code_issue",
            },
        ),
        migrations.AddField(
            model_name="classanalysis",
            name="file_analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_analyses",
                to="analyzer.fileanalysis",
            ),
        ),
        migrations.AddField(
            model_name="classanalysis",
            name="package_analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="analyzer.packageanalysis",
            ),
        ),
        migrations.CreateModel(
            name="BackendStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_time", models.FloatField()),
                ("files_processed", models.IntegerField()),
                ("issues_found", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("issues_by_severity", models.JSONField(default=dict)),
                ("issues_by_category", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "backend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="analyzer.analysisbackendmodel",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backend_statistics",
                        to="analyzer.analysissession",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_backend_statistics",
            },
        ),
        migrations.AddField(
            model_name="analysissession",
            name="flx_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_sessions",
                to="analyzer.project",
            ),
        ),
        migrations.CreateModel(
            name="AnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary Report"),
                            ("detailed", "Detailed Report"),
                            ("security", "Security Report"),
                            ("quality", "Quality Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("markdown", "Markdown"),
                            ("pdf", "PDF"),
                            ("json", "JSON"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("download_count", models.IntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="analyzer.analysissession",
                    ),
                ),
            ],
            options={
                "db_table": "analyzer_analysis_report",
            },
        ),
        migrations.AddIndex(
            model_name="analysisbackendmodel",
            index=models.Index(
                fields=["is_active", "is_available"],
                name="analyzer_ba_is_acti_960985_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analysisbackendmodel",
            index=models.Index(
                fields=["execution_order"],
                name="analyzer_ba_executi_1625fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="variableanalysis",
            index=models.Index(
                fields=["variable_type"],
                name="analyzer_va_variabl_e244a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="variableanalysis",
            index=models.Index(
                fields=["is_unused"],
                name="analyzer_va_is_unus_47c6b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="variableanalysis",
            index=models.Index(
                fields=["is_constant"],
                name="analyzer_va_is_cons_3419eb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variableanalysis",
            unique_together={("file_analysis", "name", "line_number")},
        ),
        migrations.AddIndex(
            model_name="securityissue",
            index=models.Index(
                fields=["session", "severity"],
                name="analyzer_se_session_620766_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityissue",
            index=models.Index(
                fields=["file_path"],
                name="analyzer_se_file_pa_595eed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="packageanalysis",
            index=models.Index(
                fields=["session", "name"],
                name="analyzer_pa_session_bc0f9e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="packageanalysis",
            index=models.Index(
                fields=["maintainability_score"],
                name="analyzer_pa_maintai_0ee9d4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="packageanalysis",
            unique_together={("session", "name")},
        ),
        migrations.AddIndex(
            model_name="issuetype",
            index=models.Index(
                fields=["backend", "category"],
                name="analyzer_is_backend_5ac653_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issuetype",
            index=models.Index(
                fields=["severity", "category"],
                name="analyzer_is_severit_9a2cc7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issuetype",
            index=models.Index(
                fields=["is_active"],
                name="analyzer_is_is_acti_42aa7d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issuetype",
            unique_together={("backend", "code")},
        ),
        migrations.AddIndex(
            model_name="importanalysis",
            index=models.Index(
                fields=["import_type"],
                name="analyzer_im_import__96cda9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importanalysis",
            index=models.Index(
                fields=["is_unused"],
                name="analyzer_im_is_unus_64af73_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importanalysis",
            index=models.Index(
                fields=["is_circular"],
                name="analyzer_im_is_circ_b45ca2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="importanalysis",
            unique_together={
                ("file_analysis", "module_name", "import_name", "line_number"),
            },
        ),
        migrations.AddIndex(
            model_name="functionanalysis",
            index=models.Index(
                fields=["file_analysis", "name"],
                name="analyzer_fu_file_an_344695_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="functionanalysis",
            index=models.Index(
                fields=["function_type"],
                name="analyzer_fu_functio_d7711f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="functionanalysis",
            index=models.Index(
                fields=["cyclomatic_complexity"],
                name="analyzer_fu_cycloma_683dc7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="functionanalysis",
            index=models.Index(
                fields=["complexity_level"],
                name="analyzer_fu_complex_623a29_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="functionanalysis",
            unique_together={("file_analysis", "name", "line_start")},
        ),
        migrations.AddIndex(
            model_name="fileanalysis",
            index=models.Index(
                fields=["session", "file_path"],
                name="analyzer_fi_session_46f47f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileanalysis",
            index=models.Index(
                fields=["complexity_score"],
                name="analyzer_fi_complex_ab2698_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="duplicatelocation",
            index=models.Index(
                fields=["duplicate_block", "file_path"],
                name="analyzer_du_duplica_1c0f22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="duplicatecodeblock",
            index=models.Index(
                fields=["session", "similarity_score"],
                name="analyzer_du_session_5a5310_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detectedissue",
            index=models.Index(
                fields=["session", "issue_type"],
                name="analyzer_de_session_171259_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detectedissue",
            index=models.Index(
                fields=["file_path", "line_number"],
                name="analyzer_de_file_pa_5c9469_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detectedissue",
            index=models.Index(
                fields=["is_resolved", "is_false_positive"],
                name="analyzer_de_is_reso_7427f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detectedissue",
            index=models.Index(
                fields=["detected_at"],
                name="analyzer_de_detecte_7830f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deadcodeissue",
            index=models.Index(
                fields=["session", "dead_type"],
                name="analyzer_de_session_67b449_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deadcodeissue",
            index=models.Index(
                fields=["file_path"],
                name="analyzer_de_file_pa_c0cacc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classanalysis",
            index=models.Index(
                fields=["file_analysis", "name"],
                name="analyzer_cl_file_an_bc1910_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classanalysis",
            index=models.Index(
                fields=["complexity_score"],
                name="analyzer_cl_complex_a9c599_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classanalysis",
            index=models.Index(
                fields=["method_count"],
                name="analyzer_cl_method__957b69_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classanalysis",
            unique_together={("file_analysis", "name", "line_start")},
        ),
        migrations.AddIndex(
            model_name="backendstatistics",
            index=models.Index(
                fields=["session", "status"],
                name="analyzer_ba_session_a85e9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="backendstatistics",
            index=models.Index(
                fields=["backend", "created_at"],
                name="analyzer_ba_backend_d1fa05_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="backendstatistics",
            unique_together={("session", "backend")},
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(fields=["status"], name="analyzer_an_status_85effc_idx"),
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(
                fields=["created_at"],
                name="analyzer_an_created_253686_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analysisreport",
            index=models.Index(
                fields=["session", "report_type"],
                name="analyzer_an_session_9fb349_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analysisreport",
            index=models.Index(
                fields=["created_at"],
                name="analyzer_an_created_aee3bf_idx",
            ),
        ),
    ]
